spring.application.name=spring-boot-study

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.flyway.validate-migration-naming=true

security.jwt.secret=${JWT_SECRET}
security.jwt.expiration-seconds=3600
